const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const compiler = require('vue-template-compiler');
const root = path.resolve(__dirname, '../../src');
function load(file, extra = {}) {
  const full = path.join(root, file);
  const source = fs.readFileSync(full, 'utf8');
  const sfc = file.endsWith('.vue') ? compiler.parseComponent(source) : null;
  if (sfc) {
    const compiled = compiler.compile(sfc.template.content);
    assert.deepEqual(compiled.errors, [], file + ' template compiles');
  }
  const code = (sfc ? sfc.script.content : source)
    .replace(/^import .*;?$/gm, '')
    .replace(/export default /g, 'module.exports.default = ')
    .replace(/export function (\w+)/g, 'function $1');
  const mod = { exports: {} };
  const deps = { mapGetters: () => ({}), mapActions: () => ({}), mapState: () => ({}), List: {}, BuildLogDialog: {}, Notifications: {}, codemirror: {}, moment: () => ({}), PAGE_SIZE: 100, normPaging: x => x, pagedPath: x => x, parseEnvironmentJSON: () => ({ok:true}), ...extra };
  new Function('module', ...Object.keys(deps), code + '\n' + (file === 'store/buildlog.js' ? 'module.exports.normalizeStatus = normalizeStatus; module.exports.normalizeBuildItems = normalizeBuildItems;' : ''))(mod, ...Object.values(deps));
  return mod.exports.default || mod.exports;
}
const buildlog = load('store/buildlog.js');
const buildSource = fs.readFileSync(path.join(root, 'store/buildlog.js'), 'utf8');
const normalize = new Function('PAGE_SIZE','normPaging','pagedPath', buildSource.replace(/^import .*;$/gm,'').replace('export default','const store =').replace(/export function /g,'function ') + '\nreturn {normalizeStatus, normalizeBuildItems};')(100,x=>x,x=>x);
const NOW = Date.UTC(2026,9,9,12);
assert.equal(normalize.normalizeStatus('created', NOW - 21*60000, NOW), 'TIMEOUT');
assert.equal(normalize.normalizeStatus('started', NOW - 5*60000, NOW), 'RUNNING');
assert.equal(normalize.normalizeStatus('success', NOW - 21*60000, NOW), 'OK');
assert.equal(normalize.normalizeStatus('timed out', NOW, NOW), 'TIMEOUT');
assert.equal(normalize.normalizeStatus('building', 'invalid', NOW), 'RUNNING');
assert.equal(normalize.normalizeStatus('failed', NOW - 21*60000, NOW), 'FAILED');
const flat = normalize.normalizeBuildItems([{build_id:'build-1',udid:'device-1',state:'created',date:NOW}])[0];
assert.equal(flat.build_id, 'build-1');
assert.equal(flat.udid, 'device-1');
assert.deepEqual(normalize.normalizeBuildItems([{_id:'nested', log:[{build_id:'b2',udid:'d2',log:[{message:'output'}]}]}])[0].log, ['output']);
const logModule = {exports:{}};
new Function('module', fs.readFileSync(path.join(root,'utils/buildLog.js'),'utf8').replace('export function','module.exports.buildLogText = function'))(logModule);
const text = logModule.exports.buildLogText;
assert.equal(text({contents:Buffer.from('Český log').toJSON(),log:[{message:'short'}]}),'Český log');
assert.equal(text({log:[{log:[{contents:'full'}, {message:'line'}]}]}),'full\nline');
assert.equal(text({}), '');
assert.equal(text([{message:'retained log'}]), 'retained log');
assert.equal(text('full file contents'), 'full file contents');
const api = load('core/api.js');
const client = Object.create(api.prototype);
assert.deepEqual(client.parseResult({success:true,contents:Buffer.from('log').toJSON(),log:[{message:'hi'}]}).response, {contents:Buffer.from('log').toJSON(),log:[{message:'hi'}]});
assert.deepEqual(client.parseResult({success:true,response:[1],paging:{has_more:true}}),{success:true,response:[1],paging:{has_more:true}});
const profile = load('pages/Profile/Profile.vue');
const preferences = {notifForm:{all:true,important:true,info:true}};
profile.methods.notificationChanged.call(preferences,'important',true);
assert.equal(preferences.notifForm.all,false);
profile.methods.notificationChanged.call(preferences,'all',true);
assert.equal(preferences.notifForm.important,false);
assert.equal(preferences.notifForm.info,false);
const transformers = load('store/transformers.js');
const keys = load('store/rsakeys.js');
const device = load('pages/Devices/DeviceDetail.vue');
const dialog = load('components/BuildLogDialog/BuildLogDialog.vue',{buildLogText:text});
const keyPage = load('pages/Rsakeys/Rsakeys.vue');
load('components/Header/Header.vue'); load('components/Notifications/Notifications.vue');
load('pages/History/History.vue'); load('pages/Transformers/Transformers.vue'); load('pages/Transformers/TransformerEditor.vue');
(async () => {
  let posted;
  await transformers.actions.saveTransformers.call({$api:{$post:async (url,body)=>{posted={url,body:JSON.parse(body)};return {success:true};}}},{dispatch:async()=>{}},[{utid:'t1',body:'encoded'}]);
  assert.deepEqual(posted,{url:'/profile',body:{info:{transformers:[{utid:'t1',body:'encoded'}]}}});
  await assert.rejects(()=>transformers.actions.fetchItems.call({$api:{$get:async()=>({success:false})}},{state:{items:[]},commit:()=>{throw new Error('must not clear');}}));
  let payload;
  const state={items:[{utid:'existing',alias:'Existing',body:'keep'}]};
  await transformers.actions.createItem({state,dispatch:async(action,value)=>{if(action==='saveTransformers') {payload=value; return {success:true};}}},{alias:'New',body:'// český'});
  assert.equal(payload[0].body,'keep');
  assert.equal(decodeURIComponent(escape(atob(payload[1].body))),'// český');
  let keyRequest;
  await keys.actions.createItem.call({$api:{$put:async(url,body)=>{keyRequest=JSON.parse(body);return {success:true};}}},{dispatch:async()=>{}},'Firmware');
  assert.deepEqual(keyRequest,{name:'Firmware'});
  const keyState={}; keys.mutations.saveItems(keyState,{items:[{name:'old',date:1},{name:'new',date:2}]});
  assert.equal(keyState.items[0].name,'new');
  let requested;
  await buildlog.actions.fetchBuildDetail.call({$api:{$get:async path=>{requested=path;return {success:true};}}},{},'build/id');
  assert.equal(requested,'/logs/build/build%2Fid');
  const modal = Object.assign(dialog.data(),{$store:{dispatch:async()=>({success:true,response:{contents:'FULL LOG'}})}});
  await dialog.methods.load.call(modal);
  assert.equal(modal.text,'FULL LOG'); assert.equal(modal.loading,false);
  modal.$store.dispatch=async()=>({success:false}); await dialog.methods.load.call(modal);
  assert.equal(modal.error,'Could not load this build log.'); assert.equal(modal.loading,false);
  let resolveOld;
  modal.$store.dispatch=()=>new Promise(resolve=>{resolveOld=resolve;});
  const old=dialog.methods.load.call(modal);
  modal.$store.dispatch=async()=>({success:true,response:{contents:'new'}}); await dialog.methods.load.call(modal);
  resolveOld({success:true,response:{contents:'old'}}); await old;
  assert.equal(modal.text,'new');
  let update;
  const dev=Object.assign(device.data(),{device:{udid:'d'},editForm:{transformers:['existing']},transformerForm:{alias:'New',body:'return status;'},getTransformers:()=>[],createTransformerItem:async()=>({success:true,utid:'new'}),updateDevice:async x=>{update=x;return {success:true};},loadDevice:async()=>{},$bvModal:{hide:()=>{}}});
  await device.methods.createTransformer.call(dev,{preventDefault(){}});
  assert.deepEqual(update.changes.transformers,['existing','new']); assert.equal(dev.transformerSaving,false);
  const page=Object.assign(keyPage.data(),{keyName:'Firmware',createItem:async name=>{assert.equal(name,'Firmware');return {success:true,response:{name,pubkey:'public-key'}};},showKey:keyPage.methods.showKey,loadData:async()=>{},$bvModal:{show:()=>{}}});
  await keyPage.methods.create.call(page); assert.equal(page.createdPubkey,'public-key'); assert.equal(page.creating,false);
  page.keyName='retry'; page.createItem=async()=>{throw new Error('offline');}; await keyPage.methods.create.call(page);
  assert.equal(page.creating,false); assert.ok(page.error);
  console.log('v1.16 regression checks passed: logs, API envelopes, notifications, transformers, deploy keys, and all changed Vue templates.');
})().catch(err=>{console.error(err); process.exitCode=1;});
